### PR TITLE
Update gems

### PR DESCRIPTION
**Pull request by hectorsector**
We're using an outdated version of `nokogiri` with a vulnerability. This PR should take care of that.

### CODE REVIEW

**Comment by hectorsector** [comment]
@brianamarie the snyk dependency seems to [linking to your account](https://snyk.io/org/brianamarie/test/github/githubtraining/caption-this/5ba4c26483c50250fc2a44105f4d0023c70f45e8?fromStatus=true). Could I please get your 👀 and perhaps some help figuring out what's wrong in Snyk? It doesn't seem to let me.

screen shot 2018-01-22 at 5 57 28 pm

**Comment by brianamarie** [comment]
@hectorsector I've deactivated this repository on Snyk, so I'm not sure why this check is still showing up here. 🤔 It _shouldn't_ ™️ be on new PRs, I would think. Sorry about this.

**Comment by hectorsector** [comment]
No worries ❤️ @brianamarie

**Comment by hectorsector** [comment]
In addition to the Snyk issue, this PR tries to update too much. Closing in favor of #23 which updates just the one critical vulnerability.

**Pull request closed without merging**
